hidden_nodes = [100]
learning_rate = 0.00005
NUM_EPOCHS = 700
BATCH_SIZE = -1
n_matches = -1
TEST_PORTION = 0.2
DO_MATCH_DUP = True
DO_TRAIN = False
DO_LOAD = False or DO_TRAIN
CHECKPOINT_PATH = "training_1/cp.ckpt"
SAVE_PATH = "./checkpoints/most_recent"